# Generated by Django 4.1.3 on 2023-03-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('Gender', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'others')], max_length=10)),
                ('Image', models.ImageField(upload_to='')),
                ('Rollno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.IntegerField()),
                ('Semester', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], max_length=20)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentmainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarksMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'Mech'), ('4', 'IT')], max_length=50, null=True)),
                ('FinalMarks', models.IntegerField(blank=True, null=True)),
                ('Marks', models.ManyToManyField(to='StudentApp.studentmarksmodel')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentmainmodel')),
            ],
        ),
    ]
